GET http://localhost:3000/users/
//mostrar todos los usuarios

###
GET http://localhost:3000/users/6/
//done miestra un usuario dependiendo del id q

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "Mash",
  "password": "mashleee",
  "email": "mmm1548@gmail.com"
  //para agregar un usuario
}


###
PUT http://localhost:3000/users/6
Content-Type: application/json

{
  "username": "Fer",
  "password": "jen123",
  "email": "fer2802@gmail.com"
  //para actualizar el usuario
}


###
DELETE http://localhost:3000/users/1/ 
//para eliminar 

###
POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "sol",
  "password": "1245",
  "email": "sol.48@gmail.com"
  //para decifrar la contraseña
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "sol",
  "password": "1245"
  //para iniciar el login
}

###
PUT http://localhost:3000/users/6/password
Content-Type: application/json

{
  "newPassword": "123456"
}