GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/2

###
POST http://localhost:3000/usuarios/
content-type: application/json

{
  "nombre": "lalis",
  "apellido": "Garcia",
  "email": "lalis123@gmail.com"
}

###
PUT http://localhost:3000/usuarios/1
content-type: application/json

{
  "nombre": "Yeni",
  "apellido": "garcia",
  "email": "yenigarciaa@gmail.com"
}

###
PATCH http://localhost:3000/usuarios/2
content-type: application/json

{
  "nombre": "Laliss"
}

###
DELETE http://localhost:3000/usuarios/1