GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/5

###
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombre": "Yeni",
    "apellido": "Garcia",
    "email": "Yenigarcia1515@gmail.com"
}
